# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://muellerzr.github.io/nbdev_colab/"

git_url = "https://github.com/muellerzr/nbdev_colab/tree/master/"

def custom_doc_links(name): return None
